spring:
  datasource:
#    url: jdbc:mysql://pokatika.cxj0vjpemsgj.ap-northeast-2.rds.amazonaws.com/pokatika
#    username: admin
#    password: admin1234
    url: jdbc:mysql://localhost:3306/pokatika
    username: javauser
    password: javauser
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate_fomat_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

server:
  port: 8080

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: debug